version: '3.9'

services:
  api:
    build: ./api
    ports:
      - 3001:3001
    volumes:
      - ./api:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=3001
    depends_on:
      - mongo

  # app:
  #   build: ./app
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./app:/usr/src/app
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - api

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: foobar
      MONGO_INITDB_DATABASE: yummy-yams-db
    volumes:
      - ./pastries.json:/tmp/pastries.json
      - ./importscript.sh:/docker-entrypoint-initdb.d/importscript.sh
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
