version: '3.9'

services:
  api:
    build: ./api
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./api:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=${API_PORT}
    depends_on:
      - mongo
    env_file:
      - .env

  app:
    build: ./app
    ports:
      - 3000:3000
    volumes:
      - ./app:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DBNAME}
    volumes:
      - ./pastries.json:/tmp/pastries.json
      - ./importscript.sh:/docker-entrypoint-initdb.d/importscript.sh
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    env_file:
      - .env
