version: '3.9'

services:
  api:
    build: ./api
    ports:
      - 3001:3001
    volumes:
      - ./api:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=3001
    command: ["node", "importData.js"]
    depends_on:
      - mongo

  app:
    build: ./app
    ports:
      - 3000:3000
    volumes:
      - ./app:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: foobar
    volumes:
      - ./data:/data/db
    
    mongo-express:
      container_name: docker_mongo_express
      image: mongo-express:latest
      depends_on:
      - mongo
      environment:
        - ME_CONFIG_MONGODB_SERVER=mongo
        - ME_CONFIG_MONGODB_ADMINUSERNAME=root
        - ME_CONFIG_MONGODB_ADMINPASSWORD=foobar
        - ME_CONFIG_BASICAUTH_USERNAME=admin
        - ME_CONFIG_BASICAUTH_PASSWORD=admin
      ports:
        - "8081:8081"